// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (ou VITE_SUPABASE_URL) \xE9 obrigat\xF3rio");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS ou SUPABASE_ANON_KEY \xE9 obrigat\xF3rio");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser exige um token OAuth verificado");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "Listar leads",
  description: "Lista os leads vis\xEDveis para o usu\xE1rio conectado, com busca opcional por nome, e-mail, telefone ou empresa.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Texto para buscar em nome, e-mail, telefone ou empresa."),
    temperature: z.enum(["cold", "warm", "hot"]).optional().describe("Filtra pela temperatura do lead."),
    limit: z.number().int().min(1).max(100).default(20).describe("Quantidade m\xE1xima de leads retornados.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, temperature, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("leads").select("id, name, email, phone, company, source, temperature, deal_value, next_action, last_contact_at, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (temperature) query = query.eq("temperature", temperature);
    if (search) {
      const term = `%${search.replace(/[%,]/g, "")}%`;
      query = query.or(
        `name.ilike.${term},email.ilike.${term},phone.ilike.${term},company.ilike.${term}`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Detalhar lead",
  description: "Retorna os dados completos de um lead (qualifica\xE7\xE3o BANT, origem/UTMs, valor e pr\xF3xima a\xE7\xE3o) e suas tarefas abertas.",
  inputSchema: {
    lead_id: z2.string().uuid().describe("ID do lead.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: lead, error } = await supabase.from("leads").select(
      "id, name, email, phone, company, position, source, lead_origin, lead_channel, temperature, deal_value, expected_close_date, next_action, notes, last_contact_at, bant_budget, bant_authority, bant_need, bant_timing, utm_source, utm_medium, utm_campaign, tags, created_at"
    ).eq("id", lead_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!lead) return { content: [{ type: "text", text: "Lead n\xE3o encontrado ou sem acesso." }], isError: true };
    const { data: tasks } = await supabase.from("tasks").select("id, title, status, priority, due_date, type").eq("lead_id", lead_id).neq("status", "completed").order("due_date", { ascending: true }).limit(20);
    const payload = { lead, open_tasks: tasks ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var create_lead_default = defineTool3({
  name: "create_lead",
  title: "Criar lead",
  description: "Cria um novo lead na empresa do usu\xE1rio conectado, j\xE1 atribu\xEDdo a ele. Use quando um novo contato precisa entrar no CRM.",
  inputSchema: {
    name: z3.string().trim().min(1).describe("Nome do lead."),
    email: z3.string().trim().email().optional().describe("E-mail do lead."),
    phone: z3.string().trim().min(8).optional().describe("Telefone com DDD (o DDI 55 \xE9 aplicado se ausente)."),
    company: z3.string().trim().optional().describe("Empresa do lead."),
    source: z3.string().trim().optional().describe("Origem do lead (ex.: indica\xE7\xE3o, evento)."),
    notes: z3.string().trim().optional().describe("Observa\xE7\xF5es iniciais."),
    temperature: z3.enum(["cold", "warm", "hot"]).optional().describe("Temperatura inicial do lead.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const { data: profile, error: profileError } = await supabase.from("profiles").select("organization_id").eq("id", userId).maybeSingle();
    if (profileError) return { content: [{ type: "text", text: profileError.message }], isError: true };
    if (!profile?.organization_id) {
      return { content: [{ type: "text", text: "Usu\xE1rio sem empresa vinculada." }], isError: true };
    }
    let phone = input.phone?.replace(/\D/g, "");
    if (phone && !phone.startsWith("55")) phone = `55${phone}`;
    const { data, error } = await supabase.from("leads").insert({
      organization_id: profile.organization_id,
      assigned_to: userId,
      name: input.name,
      email: input.email ?? null,
      phone: phone ?? null,
      company: input.company ?? null,
      source: input.source ?? "mcp",
      notes: input.notes ?? null,
      temperature: input.temperature ?? "cold"
    }).select("id, name, email, phone, company, temperature").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Lead criado: ${data.name} (${data.id})` }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var create_task_default = defineTool4({
  name: "create_task",
  title: "Criar tarefa",
  description: "Cria uma tarefa de follow-up para o usu\xE1rio conectado, opcionalmente vinculada a um lead.",
  inputSchema: {
    title: z4.string().trim().min(1).describe("T\xEDtulo da tarefa."),
    description: z4.string().trim().optional().describe("Detalhes da tarefa."),
    lead_id: z4.string().uuid().optional().describe("Lead relacionado."),
    due_date: z4.string().datetime().optional().describe("Vencimento em ISO 8601 (ex.: 2026-08-10T14:00:00Z)."),
    priority: z4.enum(["low", "medium", "high"]).default("medium").describe("Prioridade da tarefa.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const userId = ctx.getUserId();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({
      user_id: userId,
      created_by: userId,
      lead_id: input.lead_id ?? null,
      title: input.title,
      description: input.description ?? null,
      due_date: input.due_date ?? null,
      priority: input.priority ?? "medium",
      status: "pending"
    }).select("id, title, status, priority, due_date, lead_id").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Tarefa criada: ${data.title} (${data.id})` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/list-conversations.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_conversations_default = defineTool5({
  name: "list_conversations",
  title: "Listar conversas",
  description: "Lista as conversas de atendimento (WhatsApp, webchat, Instagram) vis\xEDveis para o usu\xE1rio conectado, com a \xFAltima mensagem de cada uma.",
  inputSchema: {
    status: z5.enum(["open", "waiting_human", "closed"]).optional().describe("Filtra pelo status da conversa."),
    channel: z5.string().trim().optional().describe("Filtra pelo canal (ex.: whatsapp, webchat, instagram)."),
    limit: z5.number().int().min(1).max(50).default(20).describe("Quantidade m\xE1xima de conversas.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, channel, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("webchat_conversations").select(
      "id, channel, status, visitor_name, visitor_phone, visitor_email, lead_id, needs_human, last_message_content, last_message_sender_type, last_message_at, created_at"
    ).order("last_message_at", { ascending: false, nullsFirst: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (channel) query = query.eq("channel", channel);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { conversations: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ljauactfinyqiqpwauzx";
var mcp_default = defineMcp({
  name: "remix-oficial-vendus-v5",
  title: "Remix Oficial Vendus v5",
  version: "0.1.0",
  instructions: "Ferramentas do CRM Vendus. Use `list_leads` e `get_lead` para consultar a carteira, `create_lead` para cadastrar novos contatos, `create_task` para agendar follow-ups e `list_conversations` para ver os atendimentos em andamento. Todas as a\xE7\xF5es rodam como o usu\xE1rio conectado e respeitam suas permiss\xF5es.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, create_lead_default, create_task_default, list_conversations_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
